<?php

declare(strict_types=1);

return [
    [
        'id' => 1,
        'name' => 'ボートレース桐生',
        'short_name' => '桐生',
        'hiragana_name' => 'ぼーとれーすきりゅう',
        'katakana_name' => 'ボートレースキリュウ',
        'english_name' => 'kiryu',
        'url' => 'http://www.kiryu-kyotei.com/',
    ],
    [
        'id' => 2,
        'name' => 'ボートレース戸田',
        'short_name' => '戸田',
        'hiragana_name' => 'ぼーとれーすとだ',
        'katakana_name' => 'ボートレーストダ',
        'english_name' => 'toda',
        'url' => 'https://www.boatrace-toda.jp/',
    ],
    [
        'id' => 3,
        'name' => 'ボートレース江戸川',
        'short_name' => '江戸川',
        'hiragana_name' => 'ぼーとれーすえどがわ',
        'katakana_name' => 'ボートレースエドガワ',
        'english_name' => 'edogawa',
        'url' => 'https://boatrace-edogawa.com/',
    ],
    [
        'id' => 4,
        'name' => 'ボートレース平和島',
        'short_name' => '平和島',
        'hiragana_name' => 'ぼーとれーすへいわじま',
        'katakana_name' => 'ボートレースヘイワジマ',
        'english_name' => 'heiwajima',
        'url' => 'https://www.heiwajima.gr.jp/',
    ],
    [
        'id' => 5,
        'name' => 'ボートレース多摩川',
        'short_name' => '多摩川',
        'hiragana_name' => 'ぼーとれーすたまがわ',
        'katakana_name' => 'ボートレースタマガワ',
        'english_name' => 'tamagawa',
        'url' => 'https://boatrace-tamagawa.com/',
    ],
    [
        'id' => 6,
        'name' => 'ボートレース浜名湖',
        'short_name' => '浜名湖',
        'hiragana_name' => 'ぼーとれーすはまなこ',
        'katakana_name' => 'ボートレースハマナコ',
        'english_name' => 'hamanako',
        'url' => 'https://www.boatrace-hamanako.jp/',
    ],
    [
        'id' => 7,
        'name' => 'ボートレース蒲郡',
        'short_name' => '蒲郡',
        'hiragana_name' => 'ぼーとれーすがまごおり',
        'katakana_name' => 'ボートレースガマゴオリ',
        'english_name' => 'gamagori',
        'url' => 'https://www.gamagori-kyotei.com/',
    ],
    [
        'id' => 8,
        'name' => 'ボートレース常滑',
        'short_name' => '常滑',
        'hiragana_name' => 'ぼーとれーすとこなめ',
        'katakana_name' => 'ボートレーストコナメ',
        'english_name' => 'tokoname',
        'url' => 'https://www.boatrace-tokoname.jp/',
    ],
    [
        'id' => 9,
        'name' => 'ボートレース津',
        'short_name' => '津',
        'hiragana_name' => 'ぼーとれーすつ',
        'katakana_name' => 'ボートレースツ',
        'english_name' => 'tsu',
        'url' => 'https://www.boatrace-tsu.com/',
    ],
    [
        'id' => 10,
        'name' => 'ボートレース三国',
        'short_name' => '三国',
        'hiragana_name' => 'ぼーとれーすみくに',
        'katakana_name' => 'ボートレースミクニ',
        'english_name' => 'mikuni',
        'url' => 'https://www.boatrace-mikuni.jp/',
    ],
    [
        'id' => 11,
        'name' => 'ボートレースびわこ',
        'short_name' => 'びわこ',
        'hiragana_name' => 'ぼーとれーすびわこ',
        'katakana_name' => 'ボートレースビワコ',
        'english_name' => 'biwako',
        'url' => 'https://www.boatrace-biwako.jp/',
    ],
    [
        'id' => 12,
        'name' => 'ボートレース住之江',
        'short_name' => '住之江',
        'hiragana_name' => 'ぼーとれーすすみのえ',
        'katakana_name' => 'ボートレーススミノエ',
        'english_name' => 'suminoe',
        'url' => 'https://www.boatrace-suminoe.jp/',
    ],
    [
        'id' => 13,
        'name' => 'ボートレース尼崎',
        'short_name' => '尼崎',
        'hiragana_name' => 'ぼーとれーすあまがさき',
        'katakana_name' => 'ボートレースアマガサキ',
        'english_name' => 'amagasaki',
        'url' => 'https://boatrace-amagasaki.jp/',
    ],
    [
        'id' => 14,
        'name' => 'ボートレース鳴門',
        'short_name' => '鳴門',
        'hiragana_name' => 'ぼーとれーすなると',
        'katakana_name' => 'ボートレースナルト',
        'english_name' => 'naruto',
        'url' => 'https://www.n14.jp/',
    ],
    [
        'id' => 15,
        'name' => 'ボートレース丸亀',
        'short_name' => '丸亀',
        'hiragana_name' => 'ぼーとれーすまるがめ',
        'katakana_name' => 'ボートレースマルガメ',
        'english_name' => 'marugame',
        'url' => 'https://www.marugameboat.jp/',
    ],
    [
        'id' => 16,
        'name' => 'ボートレース児島',
        'short_name' => '児島',
        'hiragana_name' => 'ぼーとれーすこじま',
        'katakana_name' => 'ボートレースコジマ',
        'english_name' => 'kojima',
        'url' => 'https://www.kojimaboat.jp/',
    ],
    [
        'id' => 17,
        'name' => 'ボートレース宮島',
        'short_name' => '宮島',
        'hiragana_name' => 'ぼーとれーすみやじま',
        'katakana_name' => 'ボートレースミヤジマ',
        'english_name' => 'miyajima',
        'url' => 'https://www.boatrace-miyajima.com/',
    ],
    [
        'id' => 18,
        'name' => 'ボートレース徳山',
        'short_name' => '徳山',
        'hiragana_name' => 'ぼーとれーすとくやま',
        'katakana_name' => 'ボートレーストクヤマ',
        'english_name' => 'tokuyama',
        'url' => 'https://www.boatrace-tokuyama.jp/',
    ],
    [
        'id' => 19,
        'name' => 'ボートレース下関',
        'short_name' => '下関',
        'hiragana_name' => 'ぼーとれーすしものせき',
        'katakana_name' => 'ボートレースシモノセキ',
        'english_name' => 'shimonoseki',
        'url' => 'https://www.boatrace-shimonoseki.jp/',
    ],
    [
        'id' => 20,
        'name' => 'ボートレース若松',
        'short_name' => '若松',
        'hiragana_name' => 'ぼーとれーすわかまつ',
        'katakana_name' => 'ボートレースワカマツ',
        'english_name' => 'wakamatsu',
        'url' => 'https://www.wmb.jp/',
    ],
    [
        'id' => 21,
        'name' => 'ボートレース芦屋',
        'short_name' => '芦屋',
        'hiragana_name' => 'ぼーとれーすあしや',
        'katakana_name' => 'ボートレースアシヤ',
        'english_name' => 'ashiya',
        'url' => 'https://www.boatrace-ashiya.com/',
    ],
    [
        'id' => 22,
        'name' => 'ボートレース福岡',
        'short_name' => '福岡',
        'hiragana_name' => 'ぼーとれーすふくおか',
        'katakana_name' => 'ボートレースフクオカ',
        'english_name' => 'fukuoka',
        'url' => 'https://www.boatrace-fukuoka.com/',
    ],
    [
        'id' => 23,
        'name' => 'ボートレース唐津',
        'short_name' => '唐津',
        'hiragana_name' => 'ぼーとれーすからつ',
        'katakana_name' => 'ボートレースカラツ',
        'english_name' => 'karatsu',
        'url' => 'https://www.boatrace-karatsu.jp/',
    ],
    [
        'id' => 24,
        'name' => 'ボートレース大村',
        'short_name' => '大村',
        'hiragana_name' => 'ぼーとれーすおおむら',
        'katakana_name' => 'ボートレースオオムラ',
        'english_name' => 'omura',
        'url' => 'https://omurakyotei.jp/',
    ],
];
