name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: PHPUnit ${{ matrix.phpunit-version }} on PHP ${{ matrix.php-version }} (${{ matrix.dependency-version }}, Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        phpunit-version:
          - '10.5.62'
          - '11.5.50'
          - '12.5.8'
          - '13.0'
        dependency-version:
          - prefer-lowest
          - prefer-stable
        exclude:
          - php-version: '8.1'
            phpunit-version: '11.5.50'
          - php-version: '8.1'
            phpunit-version: '12.5.8'
          - php-version: '8.2'
            phpunit-version: '12.5.8'
          - php-version: '8.1'
            phpunit-version: '13.0'
          - php-version: '8.2'
            phpunit-version: '13.0'
          - php-version: '8.3'
            phpunit-version: '13.0'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --with="phpunit/phpunit:${{ matrix.phpunit-version }}"

      - name: Run PHPUnit ${{ matrix.phpunit-version }}
        run: vendor/bin/phpunit --configuration=phpunit.xml.dist --no-progress
